let
    Source =
        SharePoint.Files(
            "https://trazarsalud.sharepoint.com/sites/VillaDolores",
            [ApiVersion = 15]
        ),

    FiltrarCarpeta =
        Table.SelectRows(
            Source,
            each Text.Contains([Folder Path],"Errores_Transmision")
        ),

    SoloExcel =
        Table.SelectRows(
            FiltrarCarpeta,
            each Text.StartsWith([Name],"Errores_Transmisión")
            and Text.EndsWith([Name],".xlsx")
        ),

    Keep =
        Table.SelectColumns(
            SoloExcel,
            {"Content","Name","Folder Path"}
        ),

    Excel =
        Table.AddColumn(
            Keep,
            "Excel",
            each Excel.Workbook([Content],null,true)
        )

in
    Excel
