let
    Source =
        SharePoint.Files(
            "https://trazarsalud.sharepoint.com/sites/VillaDolores",
            [ApiVersion = 15]
        ),

    Carpeta =
        Table.SelectRows(
            Source,
            each Text.Contains([Folder Path],"CUP")
        ),

    Excel =
        Table.SelectRows(
            Carpeta,
            each Text.EndsWith([Name],".xlsx")
        ),

    Keep =
        Table.SelectColumns(
            Excel,
            {"Content","Name","Date modified","Date created"}
        ),

    Workbook =
        Table.AddColumn(
            Keep,
            "Excel",
            each Excel.Workbook([Content],null,true)
        )

in
    Workbook
