let
    Source = Gestion_Base,
    #"Replaced Value" = Table.ReplaceValue(Source,",","",Replacer.ReplaceText,{"PacienteNombre"}),

    #"Removed Columns" = Table.RemoveColumns(#"Replaced Value",{"Content", "Item", "Kind", "Data"}),
    FK_Nomenclador = Table.AddColumn(
            #"Removed Columns",
            "FK_Nomenclador",
            each
                Text.Combine(
                    {
                        Text.From([Fecha],"es-AR"),
                        [PracticaCod]
                    },"-"
                ),
            type text
        ),
    #"Inserted Merged Column" = Table.AddColumn(FK_Nomenclador, "FK_Paciente", each Text.Combine({Text.From([Fecha], "es-AR"), [PacienteNombre], [PracticaCod]}, "-"), type text),
    #"Removed Duplicates" = Table.Distinct(#"Inserted Merged Column", {"FK_Paciente"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Removed Duplicates",{{"PracticaNombre", type text}, {"MutualCod", type text}, {"MutualNombre", type text}, {"AsociacionIntermedia", type text}, {"PrestadorNombre", type text}})
in
    #"Changed Type"
